# Exercise 4.1 Implementation of the TEBD algorithm

In [13]:
import a_mps, b_model, c_tebd
import numpy as np
import importlib

In [27]:
importlib.reload(a_mps)
importlib.reload(b_model)
importlib.reload(c_tebd)

<module 'c_tebd' from 'c:\\Users\\work\\OneDrive - TUM\\Dokumente\\Studium\\QST MSc\\FoPra\\FoPra 32\\c_tebd.py'>

## Part a)

- Read the code in the file a_mps.py. This file defines the class MPS in an objectoriented approach. In short, defining the class is defining a “type” which collects data in attributes (e.g. MPS.Bs, MPS.L) and has methods (e.g. MPS.site_expectation_value) which can use the attributes (referenced with the special first argument self) for calculations. 

- Generate an instance of the MPS class representing the state
|↑↑ . . . ↑> with the function init_spinup_MPS, for the start with L = 14 sites.

- Check that the (site) expectation values of the operators $\sigma_z = \left(\begin{matrix}
1 & 0 \\
0 & -1 
\end{matrix}\right)$ and $\sigma_x = \left(\begin{matrix}
0 & 1 \\
1 & 0 
\end{matrix}\right)$ give the expected values.

In [4]:
spinup_mps = a_mps.init_spinup_MPS(L = 14)

In [5]:
sigma_z = np.array([[1, 0], [0, -1]])
sigma_x = np.array([[0, 1], [1, 0]])

In [6]:
# Sigma z expectation value
spinup_mps.site_expectation_value(sigma_z)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
# Sigma x expectation value
spinup_mps.site_expectation_value(sigma_x)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Part b)

- Write a function similar to init_spinup_MPS, but initialize an MPS for the state|→→ · · · →>. 
- Check the expectation values again.

Hint: This state is also a product state of |→i = 1 √2
(|↑i + |↓i), so the singular values remain the same and the shape of each B is still (1,2,1). You should expect rounding errors of the order of machine precision ≈ 10−15.

In [16]:
spinright_mps = a_mps.init_spinright_MPS(L = 14)

In [19]:
# Sigma z expectation value
spinright_mps.site_expectation_value(sigma_z)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
# Sigma x expectation value
spinright_mps.site_expectation_value(sigma_x)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Part c)

Read the file b_model.py. It defines a class representing the transverse field ising model for a given choice of coupling parameters. 

- Calculate the energy for
L = 14, J = 1 and g ∈ { 0.5, 1, 1.5 } for each of the above defined two product states. 
- For later usage, extend the model or write a new model class which also
includes the longitudinal field h.

In [22]:
# Define the models with transverse field for g = 0
tf_model_05 = b_model.TFIModel(L = 14, J = 1, g = 0.5)
tf_model_10 = b_model.TFIModel(L = 14, J = 1, g = 1)
tf_model_15 = b_model.TFIModel(L = 14, J = 1, g = 1.5)

In [24]:
# Calculate energies for the spin-up state
tf_model_05.energy(spinup_mps), tf_model_10.energy(spinup_mps), tf_model_15.energy(spinup_mps), 

(-7.0, -14.0, -21.0)

In [26]:
# Calculate energies for the spin-right state
tf_model_05.energy(spinright_mps), tf_model_10.energy(spinright_mps), tf_model_15.energy(spinright_mps), 

(-12.999999999999996, -12.999999999999996, -12.999999999999996)

In [29]:
# Model with longitudinal field
tlf_model = b_model.TFIModel(L = 14, J = 1, g = 0.5, h = 1)
tlf_model.energy(spinright_mps)

-26.999999999999993